// Generated by Open Publish on every build from the published snapshot.
// Do not edit. Your changes will be overwritten. Change these in Obsidian,
// under Settings -> Open Publish -> Site options.
//
// This committed copy is the fallback used before the first publish, so that a
// fresh clone type-checks and builds. It must list every option with a sensible
// default: `fetch-content.mjs` merges the snapshot over these, so an older
// snapshot missing a key gets the default rather than `undefined`.
export const site = {
  title: 'My Notes',
  homepage: '',
  locale: 'en-US',
  dir: 'ltr',
  noIndex: false,
  showThemeToggle: true,
  strictLineBreaks: false,
  showNavigation: true,
  showSearch: true,
  showGraph: true,
  showOutline: true,
  showBacklinks: true,
  showTags: true,
  analytics: { provider: 'none', id: '' },
}
export default site
