#!/usr/bin/env node
/**
 * Step 2: run Quartz over `content/`.
 *
 * Quartz v4 is used as a checked-out repository rather than an npm package, so
 * this supports both shapes:
 *
 *   - the template repository IS a Quartz fork  -> `quartz/` already exists here
 *   - the template is a thin overlay            -> clone Quartz at a pinned ref
 *
 * The ref is pinned rather than tracking a branch so that a build which worked
 * yesterday still works today. Bump QUARTZ_REF deliberately.
 */

import { spawn } from 'node:child_process'
import { access, cp, mkdir, readdir } from 'node:fs/promises'
import { join } from 'node:path'
import process from 'node:process'

import { patchDirection } from './lib/rtl-patch.mjs'

const QUARTZ_REPO = process.env.OP_QUARTZ_REPO ?? 'https://github.com/jackyzha0/quartz.git'
const QUARTZ_REF = process.env.OP_QUARTZ_REF ?? 'v4.5.1'
const WORK_DIR = '.quartz'

const exists = (path) => access(path).then(() => true, () => false)

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { stdio: 'inherit', ...options })
    child.on('error', reject)
    child.on('exit', (code) =>
      code === 0 ? resolve() : reject(new Error(`${command} ${args.join(' ')} exited with code ${code}`)),
    )
  })
}

async function main() {
  // Shape 1: this repository is itself a Quartz checkout.
  if (await exists('quartz')) {
    console.log('[open-publish] building with the Quartz checkout in this repository')
    await run('npx', ['quartz', 'build'])
    return
  }

  // Shape 2: fetch Quartz, then build our content inside it.
  if (!(await exists(WORK_DIR))) {
    console.log(`[open-publish] fetching Quartz ${QUARTZ_REF}`)
    await run('git', ['clone', '--depth', '1', '--branch', QUARTZ_REF, QUARTZ_REPO, WORK_DIR])
  }

  await run('npm', ['ci', '--no-audit', '--no-fund'], { cwd: WORK_DIR }).catch(() =>
    run('npm', ['install', '--no-audit', '--no-fund'], { cwd: WORK_DIR }),
  )

  await mkdir(join(WORK_DIR, 'content'), { recursive: true })
  await cp('content', join(WORK_DIR, 'content'), { recursive: true, force: true })

  // op-site.ts is generated by fetch-content and imported by both config files,
  // so it has to travel with them or the build fails on a missing module.
  for (const file of ['quartz.config.ts', 'quartz.layout.ts', 'op-site.ts']) {
    if (await exists(file)) await cp(file, join(WORK_DIR, file), { force: true })
  }

  // And so does scripts/lib, for exactly the same reason: quartz.config.ts
  // imports resolveBaseUrl from it, and the config is built by esbuild from
  // inside WORK_DIR, where a relative path resolves against the copy rather
  // than the original. Missing this made every overlay build fail on "Could
  // not resolve ./scripts/lib/site-url.mjs", which is also why `npm run verify`
  // never validated this shape.
  if (await exists(join('scripts', 'lib'))) {
    await mkdir(join(WORK_DIR, 'scripts'), { recursive: true })
    await cp(join('scripts', 'lib'), join(WORK_DIR, 'scripts', 'lib'), { recursive: true, force: true })
  }

  // And `styles/`, for a third time the same reason: `quartz/styles/base.scss`
  // reaches out of the checkout for our right-to-left sheet, so the sheet has
  // to be inside the checkout for that path to mean anything.
  if (await exists('styles')) {
    await cp('styles', join(WORK_DIR, 'styles'), { recursive: true, force: true })
  }

  // In the forked shape above, assembly already did this. Here Quartz is a
  // plain clone, so the three edits that give it a direction concept at all
  // have to happen before the build. Running it against a checkout cached
  // from a previous build is a no-op.
  await patchDirection(WORK_DIR)

  await run('npx', ['quartz', 'build', '--output', '../public'], { cwd: WORK_DIR })

  const produced = await readdir('public').catch(() => [])
  console.log(`[open-publish] generator produced ${produced.length} top-level entr(ies) in public/`)
}

main().catch((error) => {
  console.error(`\n[open-publish] The site generator failed.\n\n${error.message}\n`)
  process.exit(1)
})
